# Generated by Django 5.0.6 on 2024-06-08 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='user',
        ),
    ]
